{% set version = "1.0.2" %}

package:
  name: pyppeteer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyppeteer/pyppeteer-{{ version }}.tar.gz
  sha256: 4621bb890e54f43dce84f5139ea4d484a62886be1903c2fcb393af607943538f

build:
  noarch: python
  number: 0
  entry_points:
    - pyppeteer-install = pyppeteer.command:install
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core
  run:
    - appdirs >=1.4.3,<2.0.0
    - certifi >=2021
    - importlib-metadata >=1.4
    - pyee >=8.1.0,<9.0.0
    - python >=3.7
    - tqdm >=4.42.1,<5.0.0
    - urllib3 >=1.25.8,<2.0.0
    - websockets >=10.0,<11.0

test:
  requires:
    - pip
  imports:
    - pyppeteer
  commands:
    - python -m pip check
    - export PYPPETEER_HOME=$(pwd)/tmp  # [unix]
    - set PYPPETEER_HOME=%CD%\tmp  # [win]
    - pyppeteer-install

about:
  home: https://github.com/pyppeteer/pyppeteer
  summary: Headless chrome/chromium automation library (unofficial port of puppeteer)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Headless chrome/chromium automation library (unofficial port of puppeteer)
  doc_url: https://pyppeteer.github.io/pyppeteer
  dev_url: https://github.com/pyppeteer/pyppeteer

extra:
  recipe-maintainers:
    - kiwi0fruit
    - bollwyvl
    - SylvainCorlay
